version: "3.7"
services:
  kafka:
    #profiles:
    #  - donotstart
    image: confluentinc/confluent-local:7.6.1
    hostname: kafka-pysr
    container_name: kafka-pysr
    networks:
      - pysr_net
    ports:
      - "9092:9092"
      - "19092:19092"
      - "39092:39092"
      - "49092:49092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT,SASL_DOCKER:SASL_PLAINTEXT,PLAIN_HOST:PLAINTEXT,PLAIN_HOST_DOCKER:PLAINTEXT
      KAFKA_LISTENERS: BROKER://:9092, CONTROLLER://:9093,SASL_DOCKER://:19092,PLAIN_HOST://:39092,PLAIN_HOST_DOCKER://:49092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka-anomaly:9092,SASL_DOCKER://kafka-anomaly:19092,PLAIN_HOST://localhost:39092,PLAIN_HOST_DOCKER://host.docker.internal:49092
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_jaas.conf"
    volumes:
      - ./kafka_jaas.conf:/etc/kafka/kafka_jaas.conf
      
  sr:
    image: confluentinc/cp-schema-registry:7.6.1
    hostname: sr
    container_name: sr
    ports:
      - '8081:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: sr
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: "schemas"
      # SCHEMA_REGISTRY_KAFKASTORE_SSL_ENDPOINT_IDENTIFIED_ALGORITHM: "https"
      SCHEMA_REGISTRY_KAFKASTORE_REQUEST_TIMEOUT_MS: 20000
      SCHEMA_REGISTRY_KAFKASTORE_RETRY_BACKOFF_MS: 500
      #SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: "SASL_SSL"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: host.docker.internal:49092
      #SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"alice\" password=\"alice-secret\";"
      #SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: "PLAIN"
      SCHEMA_REGISTRY_CONFLUENT_LICENSE_REPLICATION_FACTOR: 3
      # SCHEMA_REGISTRY_CONFLUENT_LICENSE: $CONFLUENT_LICENSE

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.6.1
    hostname: control-center
    container_name: control-center
    depends_on:
      - kafka
      - sr
    ports:
      - "${C3_PORT:-9021}:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: host.docker.internal:49092
      CONTROL_CENTER_KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:49092
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://sr:8081"
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      CONTROL_CENTER_KAFKA_MYCLUSTER_BOOTSTRAP_SERVERS: host.docker.internal:49092
      CONTROL_CENTER_UI_AUTOUPDATE_ENABLE: "false"
      CONTROL_CENTER_COMMAND_TOPIC_REPLICATION: 1
      CONTROL_CENTER_METRICS_TOPIC_REPLICATION: 1

  akhq:
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: host.docker.internal:49092
              schema-registry:
                url: http://host.docker.internal:8081
    ports:
      - "8082:8080"

networks:
  pysr_net:
